version: 2

build:
  provider: nixpacks
  nixpacks:
    cmds:
      - cd backend && pip install -r requirements.txt

deploy:
  startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
  restartPolicyType: always
